### ISSUE TITLE
Tool not working

### ISSUE THREAD

**Issue by Xitro01** [ad0nis/ntlm_relay_gat#2]
Hi there,

Thought I'd try out your tool. As I currently have some seperate homebrew scripts to do something like this.
The problem is that I can't seem to run the tool as it gives me an error:

```
└─$ python ntlm_relay_gat.py --smb-shares -t 10               
⠀⠀⠀⠀⠀⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⢀⡀⣈⡉⠻⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ __________________.____       _____   
⠀⢀⣾⣧⣉⠁⣠⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ \      \__    ___/|    |     /     \  
⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⡟⢸⣷⡀⠀⣀⣀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀ /   |   \|    |   |    |    /  \ /  \ 
⠀⠈⢿⣿⣿⣿⣿⣿⣿⡟⢁⣾⣿⣿⣦⠈⢿⠀⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀/    |    \    |   |    |___/    Y    \⠀
⠀⠀⠀⠙⠛⠛⠛⠛⢉⣴⣿⣿⣿⣿⣿⠇⢸⠀⠁⠶⢀⡀⠀⠀⠀⠀⠀⠀\____|__  /____|   |_______ \____|__  /
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣉⡉⠙⠛⢁⣠⣿⠀⡇⣴⠄⣁⠀⠀⠀⠀⠀⠀        \/                 \/       \/ 
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠉⠉⠉⠉⠀⠑⢠⡤⢉⠀⠀⠀⠀⠀⠀⠀__________       .__                               ⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢀⣄⠉⢉⣠⠈⠛⠒⣤⡈⠛⠀⠀⠀⠀⠀⠀\______   \ ____ |  | _____  ___.__.               ⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⠋⠀⡄⢻⣧⠀⠀⠈⣴⠙⣂⠀⠀⠀⠀⠀ |       _// __ \|  | \__  \<   |  |               ⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡿⠃⠀⠀⢸⡄⠹⣇⠀⠀⢠⣦⠈⡁⠀⠀⠀⠀ |    |   \  ___/|  |__/ __ \\___  |               ⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡿⠁⠀⠀⠀⠀⠟⠀⠹⣆⠀⠀⠠⣦⠈⣀⠀⠀⠀ |____|_  /\___  >____(____  / ____|               ⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣰⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣆⠀⠀⠀⣶⠄⠀⠀⠀⠀       \/     \/          \/\/                    
⠀⠀⠀⠀⠀⠀⠀⠈⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠁⠀⠀⠀⠶⠀⣠⡀⠀   ________        __                               
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠁⠀  /  _____/_____ _/  |_                             
"Relay Gat go brrrrrrrrrrrrrr" /   \  ___\__  \\   __\                            
                               \    \_\  \/ __ \|  |                              
 By ad0nis (Aaron Pohl)         \______  (____  /__|                              
 and fin3ss3g0d (Dylan Evans)          \/     \/                                  
 
Attempting to retrieve list of active relays from 'http://localhost:9090/ntlmrelayx/api/v1.0/relays'.
Please ensure that you have ntlmrelayx.py running with active relays showing in 'socks' command output.
Traceback (most recent call last):
  File "/home/kali/Tools/impacket/examples/ntlm_relay_gat/ntlm_relay_gat.py", line 275, in <module>
    main()
  File "/home/kali/Tools/impacket/examples/ntlm_relay_gat/ntlm_relay_gat.py", line 47, in main
    handle_relay_info(relay_info)
TypeError: handle_relay_info() missing 1 required positional argument: 'args'
```

Any idea? http://localhost:9090/ntlmrelayx/api/v1.0/relays gives me a list of relays, so that seems to be configured correctly.

**Comment by fin3ss3g0d** [comment]
Hey, thank you for pointing this out! Sorry I didn't get back to this sooner, I didn't have notifications turned on for this repository. I found the issue and fixed it. Re-open if it does not work, cheers!

**Comment by Xitro01** [comment]
Hi there,

Tested it out again.
I would advice to use proxychains with the -q parameter, to keep proxychains quiet.
And for smb-shares maybe use smbmap to get read/write status as well and some colors.
